services:
  ai-email-sorter-dev:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    container_name: ai-email-sorter-dev
    ports:
      - "3001:3000"
    volumes:
      - ../../:/app
      - /app/node_modules
      
networks:
  default:
    name: gateway
    external: true